version: "3.5"
services:
  mysql:
    image: mysql:8.0.41-debian
    container_name: virtual-file-system-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    restart: always

  redis:
    image: redis:7-alpine
    container_name: virtual-file-system-redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --save 60 1 --loglevel warning

volumes:
  mysql_db:
  redis_data:
  data:
