version: "3.5"
services:
  mysql:
    image: mysql:8.0
    container_name: virtual-file-system-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    restart: always

  fastify:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastify_template
    ports:
      - 8812:8080
    volumes:
      - .env:/app/.env
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_db:
